### ISSUE TITLE
Recenzie FX OS 2.5 2015-10-23

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-ro/localizare-FirefoxOS#1]
Listă cu erori și greșeli prezente in versiunea în lb. română a Firefox OS 2.5 
- [ ] Setări -> Imbunătățește Firefox OS #2
- [ ] Ecranul de Pinned Pages #3
- [x] Pluralul byți #4
- [ ] E-mail - Categorii standard #5
- [ ] Setări de dezvoltator #6
- [ ] Setări - Accesibilitare #7 
- [ ] Licența - Obținerea odului sursă #8 
- [ ]  Stocarea USB #9 
- [ ] Setări -> Confidențialitate navigare #10 
- [ ] Setări -> Homescreens #11 
- [ ] Setări -> Dată și oră #12 
- [ ] Setări -> Tastaturi #13 
- [ ] Setări #14 
- [ ] Aplicația Contacte #15 
- [ ] Mod dezvoltator #16 
- [ ] Navigare Privată #17 
- [ ] Ecran principal - Aplicații #18 
- [ ] Aplicație Ceas - Ora #19 
- [ ] Aplicația Marketplace - Categorii #20 
- [ ] Marketplace - Majuscula la numele categoriilor #21  
- [ ] Special Apps - not translated #22 
- [ ] Notes / Evernote - ține-mă conectat #23 
- [ ]  Spațiu la textul erorii #24 
- [ ] Introduce vs Introdu #25 
- [ ] Gasiti 501 prieteni? #26 
- [ ] Utilizare #27
